- client: !!python/object/new:p2psimpy.config.PeerType
  - PeerConfig:
      bandwidth_dl:
        Dist:
          name: norm
          params: (6553600.0, 1310720.0)
      bandwidth_ul:
        Dist:
          name: norm
          params: (6553600.0, 1310720.0)
      location:
        Dist:
          name: sample
          params: '[''Ohio'', ''Ireland'', ''Tokyo'']'
  - BaseConnectionManager: null
    MessageProducer: null
  peer: !!python/object/new:p2psimpy.config.PeerType
  - PeerConfig:
      bandwidth_dl:
        Dist:
          name: norm
          params: (6553600.0, 1310720.0)
      bandwidth_ul:
        Dist:
          name: norm
          params: (6553600.0, 1310720.0)
      location:
        Dist:
          name: sample
          params: '[''Ohio'', ''Ireland'', ''Tokyo'']'
  - BaseConnectionManager: null
    RandomDowntime:
      DowntimeConfig:
        disruption_intervals:
          DistAttr:
            name: norm
            params: (200, 100)
        disruption_time:
          DistAttr:
            name: norm
            params: (800, 200)
        start_time:
          DistAttr:
            name: norm
            params: (1500, 200)
    RangedPullGossipService:
      GossipConfig:
        exclude_types: !!set
          bootstrap: null
          client: null
- BaseConnectionManager: !!python/name:p2psimpy.services.connection_manager.BaseConnectionManager ''
  MessageProducer: !!python/name:p2psimpy.services.message_producer.MessageProducer ''
  RandomDowntime: !!python/name:p2psimpy.services.disruption.RandomDowntime ''
  RangedPullGossipService: !!python/name:p2psimpy.services.gossip.RangedPullGossipService ''
